// The panel's HTTP API reference (AST-01: everything the UI does goes
// through the documented API), generated from the route table the panel
// builds, so it can't drift from the code:
//
//   npx tsx scripts/gen-api-docs.ts           rewrite docs/api.md
//   npx tsx scripts/gen-api-docs.ts --check   exit 1 when docs/api.md is stale
//
// packages/panel/test/api-docs.test.ts fails when it is stale too.
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import type { RouteInfo } from '../packages/panel/src/app';
import { SERVER_PREFIX } from '../packages/panel/src/routes/scope';
import { makePanel } from '../packages/panel/test/harness';

export const API_DOCS = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'docs', 'api.md');

interface Schema {
  type?: string | string[];
  enum?: unknown[];
  nullable?: boolean;
  properties?: Record<string, Schema>;
  required?: string[];
  additionalProperties?: boolean | Schema;
  items?: Schema;
}

/** The routes of a panel built the way main.ts builds it (tests' fakes for the agent, the orchestrator and Discord). */
export async function apiRoutes(): Promise<RouteInfo[]> {
  const p = await makePanel();
  await p.app.ready();
  const routes = p.app.routeTable.filter((r) => r.method !== 'HEAD' && r.url.startsWith('/api/'));
  await p.app.close();
  return routes;
}

const cell = (s: string) => s.replace(/\|/g, '\\|');

/** A JSON schema in a few words: types, enums, `?` for optional properties. */
function summarise(s: Schema | undefined, depth = 0): string {
  if (!s) return 'any';
  if (s.enum) return s.enum.map((v) => JSON.stringify(v)).join(' | ');
  const type = Array.isArray(s.type) ? s.type.join(' | ') : s.type;
  let out: string;
  if (type === 'object' || s.properties) {
    const props = Object.entries(s.properties ?? {});
    if (props.length === 0 || depth >= 2) {
      const values = typeof s.additionalProperties === 'object' ? summarise(s.additionalProperties, depth + 1) : null;
      out = values ? `{ [key]: ${values} }` : 'object';
    } else {
      const req = new Set(s.required ?? []);
      out = `{ ${props.map(([k, v]) => `${k}${req.has(k) ? '' : '?'}: ${summarise(v, depth + 1)}`).join(', ')} }`;
    }
  } else if (type === 'array') {
    out = `${summarise(s.items, depth + 1)}[]`;
  } else {
    out = type ?? 'any';
  }
  return s.nullable ? `${out} | null` : out;
}

/** What a route takes: its body, query and path parameters. */
function request(r: RouteInfo): string {
  const s = (r.schema ?? {}) as { body?: Schema; querystring?: Schema; params?: Schema };
  const parts: string[] = [];
  if (s.params) parts.push(`params ${summarise(s.params)}`);
  if (s.querystring) parts.push(`query ${summarise(s.querystring)}`);
  if (s.body) parts.push(`body ${summarise(s.body)}`);
  return parts.length ? parts.map((p) => `\`${cell(p)}\``).join('<br>') : '—';
}

/** Who may call a host route. */
function access(r: RouteInfo): string {
  const c = r.config;
  if (c.auth === 'public') return 'public';
  if (c.auth === 'session') return 'session';
  if (!c.permission) return '**none**';
  return `\`${c.permission}\`${c.perServer ? ' (or on some servers: answer narrowed to them)' : ''}`;
}

export function renderApiDocs(routes: readonly RouteInfo[]): string {
  const isServer = (r: RouteInfo) => r.url === SERVER_PREFIX || r.url.startsWith(`${SERVER_PREFIX}/`);
  const host = routes.filter((r) => !isServer(r));
  const server = routes.filter(isServer);
  const lines = [
    '# HTTP API',
    '',
    'Generated by `scripts/gen-api-docs.ts` from the panel\'s route table: do not edit it by hand.',
    'Run `npx tsx scripts/gen-api-docs.ts` after changing a route; `packages/panel/test/api-docs.test.ts`',
    'fails while this file is stale (AST-01: everything the UI does goes through this API).',
    '',
    '- Every route answers JSON. Unless it is **public**, it needs a signed-in session (the `__Host-` session',
    '  cookie); **session** routes need nothing more.',
    '- Changes (POST, PUT, PATCH, DELETE) and the websocket need the exact `Origin` of the panel, and changes',
    '  the session\'s `x-gsp-csrf` header.',
    '- Permissions are defined in `packages/shared/src/permissions.ts`. Host permissions need an account of',
    '  scope `all`; a server permission is checked with the role the user has on that server.',
    '- A server the user has no role on answers `404 {"error":"server-not-found"}` on every route of it,',
    '  before anything else is checked (never 403); a capability the server\'s game lacks answers',
    '  `409 {"error":"capability-unsupported"}`.',
    '- Errors are `{"error": "<code>", …}`; the web translates the codes (`packages/web/src/i18n/*/errors.ts`).',
    '- Request shapes: `?` marks optional properties.',
    '',
    `## Host (${host.length} routes)`,
    '',
    '| Method | Path | Access | Request |',
    '|---|---|---|---|',
    ...host.map((r) => `| ${r.method} | \`${r.url}\` | ${access(r)} | ${request(r)} |`),
    '',
    `## One server: \`${SERVER_PREFIX}\` (${server.length} routes)`,
    '',
    '`:sid` is the server\'s id. The permission is checked on that server; the capability is what its game must support.',
    '',
    '| Method | Path | Permission | Capability | Request |',
    '|---|---|---|---|---|',
    ...server.map((r) => `| ${r.method} | \`${r.url}\` | \`${r.config.permission ?? 'none'}\` | ${r.config.capability ? `\`${r.config.capability}\`` : '—'} | ${request(r)} |`),
    '',
    '## Websocket: `GET /api/ws`',
    '',
    'One socket per browser tab (`session`, exact `Origin`). Every message about a server names it, and only',
    'servers the user has a role on are ever mentioned: `hello {servers: [{serverId, agentConnected, status,',
    'logs, op}]}` on connect and when a server becomes visible; `gone {serverId}` when it no longer is;',
    '`servers {}` when the list, names or the user\'s roles changed (fetch `GET /api/servers` again);',
    '`event {serverId, seq, at, event}` (agent events: `state`, `job`, `alert` need `server.view`, `players`',
    '`players.view`, `log` `log.view`); `op {serverId, op}`; `notice {serverId | null, kind, message}`;',
    '`pong` (answer to the text `ping`). See `WsMessage` in `packages/panel/src/routes/ws.ts`.',
    '',
  ];
  return lines.join('\n');
}

async function main(): Promise<void> {
  const text = renderApiDocs(await apiRoutes());
  if (process.argv.includes('--check')) {
    let current = '';
    try {
      current = readFileSync(API_DOCS, 'utf8');
    } catch {
      // missing: stale
    }
    if (current !== text) {
      console.error('docs/api.md is stale: run npx tsx scripts/gen-api-docs.ts');
      process.exit(1);
    }
    console.log('docs/api.md is up to date');
    return;
  }
  writeFileSync(API_DOCS, text);
  console.log(`Wrote ${path.relative(process.cwd(), API_DOCS)}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) await main();
